spring.application.name=siren-backend

gemini.api.key= AIzaSyActiy4xjCeEORjOsy7LwR80WjoLJS40Wc


spring.datasource.url=jdbc:mysql://localhost:3306/siren_monolithic
spring.datasource.username=root
spring.datasource.password=ammaNanna@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true